Repository newrelic/newrelic-quickstarts, pull requests merged in 2021-06, with the labels that each got.

#44 feat: adding elasticsearch pack
  .gitignore
  packs/elasticsearch/alerts/Cluster Health.yml
  packs/elasticsearch/alerts/FS Utilization Percent.yml
  packs/elasticsearch/alerts/Flush Latency Threshold.yml
  packs/elasticsearch/alerts/Index Health.yml
  packs/elasticsearch/alerts/Indexing Latency Threshold.yml
  packs/elasticsearch/alerts/JVM Heap Utilization Percent.yml
  packs/elasticsearch/alerts/Query Load Baseline.yml
  packs/elasticsearch/config.yml
  packs/elasticsearch/dashboards/elasticsearch.json
  packs/elasticsearch/dashboards/elasticsearch01.jpg
  packs/elasticsearch/dashboards/elasticsearch02.jpg
  packs/elasticsearch/dashboards/elasticsearch03.jpg
  packs/elasticsearch/dashboards/elasticsearch04.jpg
  packs/elasticsearch/icon.png
  packs/elasticsearch/instrumentation/logging/elasticsearch.yml
  packs/elasticsearch/logo.png
Labels: futurehack

#43 feat(gatsby-build): Added gatsby-build pack
  packs/gatsby-build/config.yml
  packs/gatsby-build/dashboards/gatsby-build.json
  packs/gatsby-build/dashboards/gatsby-build.png
  packs/gatsby-build/icon.png
  packs/gatsby-build/logo.png
Labels: futurehack

#40 feat: add golden signals pack
  packs/golden-signals-web/alerts/cpu.yml
  packs/golden-signals-web/alerts/errors.yml
  packs/golden-signals-web/alerts/memory.yml
  packs/golden-signals-web/alerts/response_time.yml
  packs/golden-signals-web/alerts/throughput.yml
  packs/golden-signals-web/config.yml
  packs/golden-signals-web/dashboards/dashboard.png
  packs/golden-signals-web/dashboards/golden_signals.json
  packs/golden-signals-web/icon.jpeg
  packs/golden-signals-web/logo.png
Labels: futurehack, opensource enablement, sp:1

#51 chore: update contributor guide
  CONTRIBUTING.md
Labels: automation, blocked, documentation, o11y
