Repository newrelic/newrelic-quickstarts, pull requests merged in 2021-09, with the labels that each got.

#182 feat(apis): added event,log,metric and trace API packs
  packs/apis/event/config.yml
  packs/apis/event/icon.png
  packs/apis/event/logo.png
  packs/apis/logs/config.yml
  packs/apis/logs/icon.png
  packs/apis/logs/logo.png
  packs/apis/metric/config.yml
  packs/apis/metric/icon.png
  packs/apis/metric/logo.png
  packs/apis/trace/config.yml
  packs/apis/trace/icon.png
  packs/apis/trace/logo.png
Labels: new-pack, support-level:newrelic

#192 chore: updates golden sig+ contributor file fixes
  CONTRIBUTING.md
  packs/golden-signals-web/dashboards/golden_signals01.png
Labels: sp:1

#203 feat: add initial install plans
  docs/config-spec.md
  docs/example-schemas/config.json
  docs/install-spec.md
  install/apm/python/install.yml
  install/apm/ruby/install.yml
  install/infrastructure/infra-agent-standard/install.yml
  install/infrastructure/infra-agent-targeted/install.yml
  install/on-host-integration/mysql/install.yml
  packs/infrastructure/config.yml
  utils/schemas/install_config.json
  utils/schemas/main_config.json
  utils/validate_packs.js
Labels: support-level:newrelic

#206 Fix: Add template and style to contributing guide
  CONTRIBUTING.md
Labels: documentation

#208 Add period to description
  packs/apache/config.yml
Labels: support-level:newrelic

#222 feat: Trend Micro Cloud One - Conformity Quick start fixes
  packs/trendmicro-cloudone-conformity/config.yml
  packs/trendmicro-cloudone-conformity/dashboards/my-dashboard.png
  packs/trendmicro-cloudone-conformity/dashboards/trendmicro-cloudone-conformity.json
  packs/trendmicro-cloudone-conformity/dashboards/trendmicro-cloudone-conformity.png
  packs/trendmicro-cloudone-conformity/icon.png
  packs/trendmicro-cloudone-conformity/logo.png
Labels: new-pack, support-level:community, in-review

#207 feat(databricks) : adding databricks pack
  packs/databricks/config.yml
  packs/databricks/dashboards/databricks.json
  packs/databricks/dashboards/databricks.png
  packs/databricks/icon.png
  packs/databricks/logo.png
Labels: waiting on contributor

#232 Add ids
  packs/databricks/config.yml
Labels: support-level:community

#231 fix: restructure and remove quickstarts
  packs/dotnet/jayrock/config.yml
  packs/dotnet/jayrock/icon.svg
  packs/dotnet/jayrock/logo.svg
  packs/golang/go-insights/config.yml
  packs/golang/go-insights/icon.svg
  packs/golang/go-insights/logo.svg
  packs/java/datastax-cassandra/config.yml
  packs/java/datastax-cassandra/icon.svg
  packs/java/datastax-cassandra/logo.svg
  packs/mysql/config.yml
  packs/python/dropbox/config.yml
  packs/python/dropbox/icon.svg
  packs/python/dropbox/logo.svg
  packs/python/pywapi/config.yml
  packs/python/pywapi/icon.svg
  packs/python/pywapi/logo.svg
  packs/python/urllib/config.yml
  packs/python/urllib/icon.svg
  packs/python/urllib/logo.svg
  packs/python/urllib2/config.yml
  packs/python/urllib2/icon.svg
  packs/python/urllib2/logo.svg
  packs/python/urllib3/config.yml
  packs/python/urllib3/icon.svg
  packs/python/urllib3/logo.svg
Labels: support-level:newrelic, support-level:community

#241 Add heroku and algorithmia
  install/logs/heroku/install.yml
  install/mlops/algorithmia/install.yml
  packs/heroku/config.yml
  packs/heroku/icon.png
  packs/heroku/logo.svg
  packs/mlops/algorithmia/config.yml
  packs/mlops/algorithmia/dashboards/algorithmia.json
  packs/mlops/algorithmia/dashboards/algorithmia.png
  packs/mlops/algorithmia/icon.svg
  packs/mlops/algorithmia/logo.svg
Labels: new-pack, support-level:newrelic

#209 Java, Nodejs, Python and .NET
  packs/dotnet/dotnet/alerts/ADPEXScore.yml
  packs/dotnet/dotnet/alerts/MemoryUsage.yml
  packs/dotnet/dotnet/alerts/TransactionsError.yml
  packs/dotnet/dotnet/config.yml
  packs/dotnet/dotnet/dashboards/dotnet.json
  packs/dotnet/dotnet/dashboards/dotnet.png
  packs/dotnet/dotnet/dashboards/dotnet02.png
  packs/dotnet/dotnet/dashboards/dotnet03.png
  packs/dotnet/dotnet/images/Errors.png
  packs/dotnet/dotnet/images/Transactions.png
  packs/dotnet/dotnet/images/VM-metrics.png
  packs/java/java/alerts/HighCpuUtilization.yml
  packs/java/java/alerts/TransactionErrors.yml
  packs/java/java/config.yml
  packs/java/java/dashboards/Java.png
  packs/java/java/dashboards/Java01.png
  packs/java/java/dashboards/Java03.png
  packs/java/java/dashboards/java.json
  packs/java/java/images/Errors.png
  packs/java/java/images/Transactions.png
  packs/java/java/images/VM-metrics.png
  packs/node-js/node-js/alerts/AdpexScore.yml
  packs/node-js/node-js/alerts/cpuUtil.yml
  packs/node-js/node-js/config.yml
  packs/node-js/node-js/dashboards/node01.png
  packs/node-js/node-js/dashboards/nodejs.json
  packs/node-js/node-js/dashboards/nodejs.png
  packs/node-js/node-js/dashboards/nodejs02.png
  packs/node-js/node-js/images/Errors.png
  packs/node-js/node-js/images/Transactions.png
  packs/node-js/node-js/images/VM-metrics.png
  packs/python/python/alerts/ADPEXScore.yml
  packs/python/python/alerts/CPUUtilization.yml
  packs/python/python/alerts/TransactionError.yml
  packs/python/python/config.yml
  packs/python/python/dashboards/python.json
  packs/python/python/dashboards/python.png
  packs/python/python/dashboards/python02.png
  packs/python/python/dashboards/python03.png
  packs/python/python/images/Errors.png
  packs/python/python/images/Transactions.png
  packs/python/python/images/VM-metrics.png
Labels: waiting on contributor

#260 Added synthetics
  packs/synthetics/availability/config.yml
  packs/synthetics/availability/icon.jpeg
  packs/synthetics/availability/logo.png
  packs/synthetics/endpoint-availability/config.yml
  packs/synthetics/endpoint-availability/icon.jpeg
  packs/synthetics/endpoint-availability/logo.png
  packs/synthetics/page-link-crawler/config.yml
  packs/synthetics/page-link-crawler/icon.jpeg
  packs/synthetics/page-link-crawler/logo.png
  packs/synthetics/page-load-performance/config.yml
  packs/synthetics/page-load-performance/icon.jpeg
  packs/synthetics/page-load-performance/logo.png
  packs/synthetics/ssl-certification-check/config.yml
  packs/synthetics/ssl-certification-check/icon.jpeg
  packs/synthetics/ssl-certification-check/logo.png
  packs/synthetics/user-flow/config.yml
  packs/synthetics/user-flow/icon.jpeg
  packs/synthetics/user-flow/logo.png
  packs/synthetics/user-step-execution/config.yml
  packs/synthetics/user-step-execution/icon.jpeg
  packs/synthetics/user-step-execution/logo.png
Labels: waiting on contributor

#259 chore: improve description for opencensus, opentelemetry and prometheus
  packs/opencensus/config.yml
  packs/opentelemetry/config.yml
  packs/prometheus/config.yml
Labels: waiting on contributor

#179 Update gatsby-build.json
  packs/gatsby-build/dashboards/gatsby-build.json
Labels: blocked, innovation, waiting on contributor

#252 chore: create redis quickstart description
  packs/redis/config.yml
Labels: waiting on contributor

#250 chore: create apache monitoring quickstart
  packs/apache/config.yml
Labels: waiting on contributor

#248 chore: create PHP monitoring quickstart
  packs/php/php/config.yml
Labels: waiting on contributor

#243 chore: Node.js Quickstart Description and Summary
  packs/node-js/node-js/config.yml
Labels: waiting on contributor

#247 chore: create MySQL quickstart kit
  packs/mysql/config.yml
Labels: waiting on contributor

#293 feat (IBM MQ) : Adding pack for New Relic IBM MQ Monitor that allows monitoring the performance of IBM MQ Objects
  packs/ibmmq/config.yml
  packs/ibmmq/dashboards/ibmmq.json
  packs/ibmmq/dashboards/ibmmq.png
  packs/ibmmq/icon.png
  packs/ibmmq/logo.png
Labels: waiting on contributor

#326 Only comment on PR opening
  .github/workflows/pr-open.yml
Labels: triage-needed

#327 fixed H1 header
  packs/dotnet/dotnet/config.yml
Labels: triage-needed

#298 chore: create Kafka quickstart description
  packs/kafka/config.yml
Labels: waiting on contributor

#333 chore: reduce Kafka description to 2000 chars
  packs/kafka/config.yml
Labels: triage-needed

#334 fix(ruby): fix reference to agent
  packs/ruby/acts-as-solr/config.yml
  packs/ruby/authlogic/config.yml
  packs/ruby/bunny/config.yml
  packs/ruby/curb/config.yml
  packs/ruby/dalli/config.yml
  packs/ruby/delayed-job/config.yml
  packs/ruby/excon/config.yml
  packs/ruby/grape/config.yml
  packs/ruby/httpclient/config.yml
  packs/ruby/httprb/config.yml
  packs/ruby/net-http/config.yml
  packs/ruby/padrino/config.yml
  packs/ruby/passenger/config.yml
  packs/ruby/puma/config.yml
  packs/ruby/rack/config.yml
  packs/ruby/rails/config.yml
  packs/ruby/rainbows/config.yml
  packs/ruby/rake/config.yml
  packs/ruby/resque/config.yml
  packs/ruby/sequel/config.yml
  packs/ruby/sidekiq/config.yml
  packs/ruby/sinatra/config.yml
  packs/ruby/sunspot/config.yml
  packs/ruby/thin/config.yml
  packs/ruby/typhoeus/config.yml
  packs/ruby/unicorn/config.yml
  packs/ruby/webrick/config.yml
Labels: triage-needed

#335 Added grafana integration and migration quickstarts
  packs/grafana/grafana-dashboard-migration/config.yml
  packs/grafana/grafana-dashboard-migration/icon.png
  packs/grafana/grafana-dashboard-migration/logo.png
  packs/grafana/grafana-prometheus-integration/config.yml
  packs/grafana/grafana-prometheus-integration/icon.png
  packs/grafana/grafana-prometheus-integration/logo.png
Labels: triage-needed

#328 improve validation output (for null description of dashboard)
  utils/__tests__/validate_packs.test.js
  utils/schemas/dashboard_config.json
  utils/validate_packs.js
Labels: triage-needed

#347 fix: update directory for release workflow
  .github/workflows/release.yml
Labels: triage-needed

#348 fix: set fetch depth and lock semantic release ver
  .github/workflows/release.yml
Labels: triage-needed

#350 fix: explicitly check `main` during release
  .github/workflows/release.yml
Labels: triage-needed

#355 fix: reduce nginx quickstart description length
  quickstarts/nginx/config.yml
Labels: triage-needed

#354 "feat([quickstart]): Added [fastly]"
  install/third-party/fastly/install.yml
  packs/fastly/alerts/fastly-errorcount.yml
  packs/fastly/alerts/fastly-responsetime.yml
  packs/fastly/config.yml
  packs/fastly/dashboards/fastly-cdn.json
  packs/fastly/dashboards/fastly-cdn01.png
  packs/fastly/logo.png
Labels: triage-needed

#357 Combining SearchNurture PRs for Prometheus, Infrastructure, Java
  quickstarts/infrastructure/config.yml
  quickstarts/java/java/config.yml
  quickstarts/prometheus/config.yml
Labels: triage-needed

#358 chore: fix wrong reference to node.js agent
  quickstarts/ruby/activerecord/config.yml
  quickstarts/ruby/ruby/config.yml
Labels: triage-needed

#359 fix(fastly): moved from packs to quickstarts
  quickstarts/fastly/alerts/fastly-errorcount.yml
  quickstarts/fastly/alerts/fastly-responsetime.yml
  quickstarts/fastly/config.yml
  quickstarts/fastly/dashboards/fastly-cdn.json
  quickstarts/fastly/dashboards/fastly-cdn01.png
  quickstarts/fastly/logo.png
Labels: triage-needed

#360 Added windows desktop, server and Mac OS
  quickstarts/macos/config.yml
  quickstarts/macos/icon.png
  quickstarts/macos/logo.png
  quickstarts/windows/windows-desktop/config.yml
  quickstarts/windows/windows-desktop/icon.svg
  quickstarts/windows/windows-desktop/logo.svg
  quickstarts/windows/windows-event-log/config.yml
  quickstarts/windows/windows-event-log/icon.svg
  quickstarts/windows/windows-event-log/logo.svg
  quickstarts/windows/windows-server/config.yml
  quickstarts/windows/windows-server/icon.svg
  quickstarts/windows/windows-server/logo.svg
Labels: triage-needed

#369 Added K8s dashboard
  quickstarts/kubernetes/kubernetes/dashboards/kubernetes.json
  quickstarts/kubernetes/kubernetes/dashboards/kubernetes.png
Labels: triage-needed

#365 fix: incorrect description for mac Os
  quickstarts/macos/config.yml
Labels: triage-needed

#370 fix(kubernetes): add pixie to keywords
  quickstarts/kubernetes/kubernetes/config.yml
Labels: triage-needed

#353 chore: update script to reword footer
  utils/schema-doc-generator/script.py
Labels: triage-needed

#362 chore: update description for Cassandra quickstart
  quickstarts/cassandra/config.yml
Labels: triage-needed

#363 chore: update RabbitMQ quickstart description
  quickstarts/rabbitmq/config.yml
Labels: triage-needed

#372 chore: update Varnish description
  quickstarts/varnish/config.yml
Labels: triage-needed

#364 feat: add documentation data source to gatsby build
  quickstarts/gatsby-build/config.yml
Labels: triage-needed

#352 chore: create Python quickstart description
  quickstarts/python/python/config.yml
Labels: triage-needed

#373 feat: Add featured keyword to partner quickstarts
  quickstarts/apache/config.yml
  quickstarts/cribl_logstream/config.yml
  quickstarts/fastly/config.yml
  quickstarts/network-data-ingest-and-cardinality/config.yml
  quickstarts/network-flow-devices/config.yml
  quickstarts/network-routers-and-switches/config.yml
  quickstarts/trendmicro-cloudone-conformity/config.yml
Labels: triage-needed

#374 Improve descriptions for EJB, Nagios, Zipkin
  quickstarts/ejb-session-beans/config.yml
  quickstarts/java/ejb-session-beans/alerts/HighCpuUtilization.yml
  quickstarts/java/ejb-session-beans/alerts/TransactionErrors.yml
  quickstarts/java/ejb-session-beans/config.yml
  quickstarts/java/ejb-session-beans/dashboards/java.json
  quickstarts/java/ejb-session-beans/dashboards/java.png
  quickstarts/java/ejb-session-beans/dashboards/java01.png
  quickstarts/java/ejb-session-beans/dashboards/java02.png
  quickstarts/java/ejb-session-beans/icon.svg
  quickstarts/java/ejb-session-beans/logo.svg
  quickstarts/nagios/config.yml
  quickstarts/zipkin/config.yml
Labels: triage-needed

#375 chore: fix agent reference
  install/apm/python/install.yml
Labels: triage-needed

#376 Added and improved some installPlans
  install/network/flow/install.yml
  install/on-host-integration/ibm-mq/install.yml
  quickstarts/ibmmq/config.yml
  quickstarts/network-flow-devices/config.yml
  quickstarts/php/silex/config.yml
Labels: triage-needed

#379 Marked Istio adapter as deprecated
  quickstarts/istio/config.yml
Labels: waiting on contributor

#382 chore: Improve description for alerting quickstarts
  quickstarts/pagerduty/pagerduty/config.yml
  quickstarts/slack/config.yml
  quickstarts/victorops/config.yml
  quickstarts/xmatters/config.yml
Labels: triage-needed

#384 chore: improve lamp description, add summary
  quickstarts/lamp/config.yml
Labels: triage-needed

#386 Update kubernetes.json
  quickstarts/kubernetes/kubernetes/dashboards/kubernetes.json
Labels: triage-needed

#385 chore: corrected support level
  CONTRIBUTING.md
Labels: triage-needed

#391 feat(quickstarts): add k8s keyword
  quickstarts/aws/amazon-eks-on-aws-fargate/config.yml
  quickstarts/cloudfoundry/config.yml
  quickstarts/kubernetes/google-kubernetes-engine/config.yml
  quickstarts/kubernetes/kubernetes-plugin-for-logs/config.yml
  quickstarts/kubernetes/kubernetes/config.yml
  quickstarts/redhat/red-hat-openshift/config.yml
  quickstarts/vmware/vmware-tanzu/config.yml
Labels: triage-needed

#396 chore(logo): updated pack logo
  quickstarts/cribl_logstream/Cribl-Logo.png
  quickstarts/cribl_logstream/config.yml
  quickstarts/cribl_logstream/logo.svg
Labels: triage-needed

#397 feat(Kentik): Added Firehose quickstart and updated NPM logos
  install/third-party/kentik/install.yml
  quickstarts/kentik/config.yml
  quickstarts/kentik/dashboards/network-flow-devices.json
  quickstarts/kentik/dashboards/network-flow-devices01.png
  quickstarts/kentik/dashboards/network-flow-devices02.png
  quickstarts/kentik/dashboards/network-synthetics.json
  quickstarts/kentik/dashboards/network-synthetics01.png
  quickstarts/kentik/logo.png
  quickstarts/network-data-ingest-and-cardinality/logo.png
  quickstarts/network-flow-devices/logo.png
  quickstarts/network-routers-and-switches/logo.png
Labels: triage-needed

#398 fix: sentence-case headers
  quickstarts/apache/config.yml
  quickstarts/dotnet/dotnet/config.yml
  quickstarts/haproxy/config.yml
  quickstarts/infrastructure/config.yml
  quickstarts/java/java/config.yml
  quickstarts/kafka/config.yml
  quickstarts/mysql/config.yml
  quickstarts/nginx/config.yml
  quickstarts/node-js/node-js/config.yml
  quickstarts/php/php/config.yml
  quickstarts/prometheus/config.yml
  quickstarts/python/python/config.yml
  quickstarts/redis/config.yml
  quickstarts/varnish/config.yml
Labels: triage-needed

#404 Network fixes
  install/network/snmp/install.yml
  quickstarts/network-data-ingest-and-cardinality/config.yml
  quickstarts/network-flow-devices/config.yml
  quickstarts/network-routers-and-switches/config.yml
Labels: triage-needed
