Repository newrelic/newrelic-quickstarts, pull requests merged in 2021-10, with the labels that each got.

#412 fix: remove dupe uuid to generate fresh
  quickstarts/databricks/config.yml
Labels: triage-needed

#413 feat: check for uuid uniqueness
  .github/workflows/validate_packs.yml
  utils/__tests__/check_quickstart_uniqueness.test.js
  utils/check_quickstart_uniqueness.js
  utils/package.json
Labels: triage-needed

#420 chore: explicit checkout for release
  .github/workflows/release.yml
Labels: eng

#403 feat(elixir): add elixir agent quickstart
  install/apm/elixir/install.yml
  quickstarts/elixir/config.yml
  quickstarts/elixir/icon.svg
  quickstarts/elixir/logo.svg
Labels: in-review

#408 First commit for the Lacework quickstart
  quickstarts/lacework/config.yml
  quickstarts/lacework/dashboards/lacework-anomaly-detections.json
  quickstarts/lacework/dashboards/lacework-anomaly-detections.png
  quickstarts/lacework/dashboards/lacework-compliance-violations.json
  quickstarts/lacework/dashboards/lacework-compliance-violations.png
  quickstarts/lacework/dashboards/lacework-security-overview.json
  quickstarts/lacework/dashboards/lacework-security-overview.png
Labels: in-review

#410 feat: add Deeper Network quickstart
  install/third-party/deeper-network/install.yml
  quickstarts/deeper-network/alerts/cpu.yml
  quickstarts/deeper-network/alerts/memory.yml
  quickstarts/deeper-network/alerts/temperature.yml
  quickstarts/deeper-network/config.yml
  quickstarts/deeper-network/dashboards/deeper-connect.json
  quickstarts/deeper-network/dashboards/deeperconnect01.png
  quickstarts/deeper-network/dashboards/deeperconnect02.png
  quickstarts/deeper-network/icon.png
  quickstarts/deeper-network/logo.png
Labels: in-review

#423 feat: dashboard showing data ingestion breakdown
  quickstarts/account-data-ingestion/config.yml
  quickstarts/account-data-ingestion/dashboards/data_ingestion_breakdown.json
Labels: triage-needed

#428 chore: adding docs to config for network data ingest
  quickstarts/network-data-ingest-and-cardinality/config.yml
Labels: triage-needed

#431 feat: add tdp install plan
  install/telemetry-data-platform/install.yml
  quickstarts/account-data-ingestion/config.yml
Labels: triage-needed

#436 chore: update quickstart
  quickstarts/dotnet/dotnet/config.yml
Labels: triage-needed

#443 chore: update quickstart for internal linking
  quickstarts/nginx/config.yml
Labels: triage-needed, failed check

#441 chore: update quickstart for internal linking
  quickstarts/java/java/config.yml
Labels: triage-needed, failed check

#456 chore: Add video link to TrendMicro quickstart
  quickstarts/trendmicro-cloudone-conformity/config.yml
Labels: triage-needed

#445 chore: update quickstart for internal linking
  quickstarts/rabbitmq/config.yml
Labels: triage-needed

#458 feat(kubernetes): add k8s install plan
  install/guided-install/default/install.yml
  install/guided-install/kubernetes/install.yml
  quickstarts/kubernetes/kubernetes/config.yml
Labels: triage-needed

#465 feat(Pixie): Added Pixie dashboards and alerts quickstart
  quickstarts/pixie/alerts/service-errors-static-alert.yml
  quickstarts/pixie/alerts/service-response-time-baseline-alert.yml
  quickstarts/pixie/alerts/service-throughput-baseline-alert.yml
  quickstarts/pixie/config.yml
  quickstarts/pixie/dashboards/pixie-quickstart.json
  quickstarts/pixie/dashboards/pixie-quickstart01.jpg
  quickstarts/pixie/dashboards/pixie-quickstart02.jpg
  quickstarts/pixie/dashboards/pixie-quickstart03.jpg
  quickstarts/pixie/pixie-horizontal-color.png
  quickstarts/pixie/pixie-icon-color.png
Labels: triage-needed

#468 Update config.yml
  quickstarts/pixie/config.yml
Labels: triage-needed

#471 Update config.yml
  quickstarts/pixie/config.yml
Labels: triage-needed

#466 feat(Pixie): Fixed static alert valueFunction parameter
  quickstarts/pixie/alerts/service-errors-static-alert.yml
  quickstarts/pixie/config.yml
Labels: triage-needed

#464 Add logging keywords
  quickstarts/infrastructure/config.yml
Labels: triage-needed

#470 Update pr-project-board.yml
  .github/workflows/pr-project-board.yml
Labels: triage-needed

#435 chore: refresh Mongodb quickstart
  quickstarts/mongodb/config.yml
Labels: content review needed, failed check

#480 chore(newrelic-npm): Update installplan for SNMP and Network Flows
  install/network/flow/install.yml
  install/network/npm/install.yml
  install/network/snmp/install.yml
  quickstarts/network-flow-devices/config.yml
  quickstarts/network-routers-and-switches/config.yml
Labels: triage-needed

#484 chore: added helper images
  CONTRIBUTING.md
  images/alerts.png
  images/dashboards.png
  images/data-sources.png
  images/install-plan.png
  images/main.png
Labels: triage-needed

#493 fix: change name and title to CodeStream
  quickstarts/codestream/config.yml
Labels: triage-needed

#521 feat(opentelemetry): improved description and added some more keywords
  quickstarts/opentelemetry/config.yml
Labels: waiting on contributor
