Repository newrelic/newrelic-quickstarts, pull requests merged in 2021-11, with the labels that each got.

#540 fix: change typo in quickstart name
  quickstarts/account-data-ingestion/config.yml
Labels: triage-needed

#538 chore: added author instructions
  CONTRIBUTING.md
Labels: triage-needed

#527 sanitize dashboard tool
  README.md
  utils/package.json
  utils/sanitize_dashboards.js
Labels: eng

#501 feat(pack) Added CherryPy pack
  quickstarts/python/cherrypy/alerts/HighMemoryUsage.yml
  quickstarts/python/cherrypy/alerts/LowApdexScore.yml
  quickstarts/python/cherrypy/config.yml
  quickstarts/python/cherrypy/dashboards/cherrypy.json
  quickstarts/python/cherrypy/dashboards/cherrypy.png
  quickstarts/python/cherrypy/dashboards/cherrypy02.png
  quickstarts/python/cherrypy/dashboards/cherrypy03.png
  quickstarts/python/cherrypy/dashboards/python.png
  quickstarts/python/cherrypy/dashboards/python02.png
  quickstarts/python/cherrypy/dashboards/python03.png
  quickstarts/python/cherrypy/images/Errors.png
  quickstarts/python/cherrypy/images/Transactions.png
  quickstarts/python/cherrypy/images/VM-metrics.png
Labels: waiting on contributor

#535 chore(delphix): Added logo reference to config yaml
  quickstarts/delphix/config.yml
Labels: triage-needed

#502 feat(pack) Added totally new pack, fastAPI. Python web framework for …
  quickstarts/python/fastapi/alerts/CPUUtilization.yml
  quickstarts/python/fastapi/alerts/HighMemoryUsage.yml
  quickstarts/python/fastapi/alerts/LowApdexScore.yml
  quickstarts/python/fastapi/alerts/TransactionError.yml
  quickstarts/python/fastapi/config.yml
  quickstarts/python/fastapi/dashboards/fastAPI-02.png
  quickstarts/python/fastapi/dashboards/fastAPI-03.png
  quickstarts/python/fastapi/dashboards/fastAPI.json
  quickstarts/python/fastapi/dashboards/fastAPI.png
  quickstarts/python/fastapi/icon.svg
  quickstarts/python/fastapi/images/Errors.png
  quickstarts/python/fastapi/images/Transactions.png
  quickstarts/python/fastapi/images/VM-metrics.png
  quickstarts/python/fastapi/logo.png
Labels: waiting on contributor, stale, failed check

#536 fix: small name change to make it clear it's the apache webserver
  quickstarts/apache/config.yml
Labels: waiting on contributor, failed check

#524 feat: added full stack observability quickstart
  quickstarts/full-stack-observability/config.yml
  quickstarts/full-stack-observability/dashboards/full-stack-observability.json
  quickstarts/full-stack-observability/dashboards/full-stack-observability.png
  quickstarts/full-stack-observability/dashboards/full-stack-observability1.png
  quickstarts/full-stack-observability/dashboards/full-stack-observability2.png
  quickstarts/full-stack-observability/dashboards/full-stack-observability3.png
  quickstarts/full-stack-observability/dashboards/full-stack-observability4.png
  quickstarts/full-stack-observability/icon.jpeg
  quickstarts/full-stack-observability/logo.png
Labels: in-review

#523 feat(sendgrid): Add installPlans for SendGrid Event Webhook and S3 log ingestion
  install/aws/aws-log-ingestion-s3/install.yml
  install/third-party/sendgrid/install.yml
  quickstarts/sendgrid/config.yml
Labels: waiting on contributor

#534 feat(pack) Added Amazon Athena
  quickstarts/aws/amazon-athena/config.yml
  quickstarts/aws/amazon-athena/dashboards/athena.json
  quickstarts/aws/amazon-athena/dashboards/athena.png
Labels: waiting on contributor, content review needed

#531 Added Amazon QLDB pack
  quickstarts/aws/aws-qldb/config.yml
  quickstarts/aws/aws-qldb/dashboards/qldb.json
  quickstarts/aws/aws-qldb/dashboards/qldb.png
Labels: waiting on contributor, content review needed, failed check

#551 chore: update Kubernetes quickstart description
  quickstarts/kubernetes/kubernetes/config.yml
Labels: triage-needed

#553 chore: update websphere liberty profile quickstart
  quickstarts/java/websphere-liberty-profile/config.yml
Labels: triage-needed

#552 chore: update httprouter quickstart description
  quickstarts/golang/httprouter/config.yml
Labels: triage-needed

#550 feat(pack): Added Netty
  quickstarts/java/netty/alerts/CPUUtilization.yml
  quickstarts/java/netty/alerts/HighMemoryUsage.yml
  quickstarts/java/netty/alerts/LowApdexScore.yml
  quickstarts/java/netty/alerts/TransactionError.yml
  quickstarts/java/netty/config.yml
  quickstarts/java/netty/dashboards/java.png
  quickstarts/java/netty/dashboards/java01.png
  quickstarts/java/netty/dashboards/java02.png
  quickstarts/java/netty/dashboards/netty.json
  quickstarts/java/netty/dashboards/netty.png
  quickstarts/java/netty/dashboards/netty01.png
  quickstarts/java/netty/dashboards/netty02.png
Labels: triage-needed

#532 Audit dashboard (migration from dashboards-library)
  quickstarts/audit/account-data-ingestion-analysis/config.yml
  quickstarts/audit/account-data-ingestion-analysis/dashboards/data_ingestion_breakdown.json
  quickstarts/audit/audit-events-analysis/config.yaml
  quickstarts/audit/audit-events-analysis/dashboards/audit.json
  quickstarts/audit/audit-events-analysis/dashboards/audit.png
  quickstarts/audit/k8s-data-ingestion-analysis/config.yaml
  quickstarts/audit/k8s-data-ingestion-analysis/dashboards/k8s-data-ingest-analysis.json
  quickstarts/audit/k8s-data-ingestion-analysis/dashboards/k8s-data-ingest-analysis01.png
  quickstarts/audit/k8s-data-ingestion-analysis/dashboards/k8s-data-ingest-analysis02.png
  quickstarts/audit/k8s-data-ingestion-analysis/dashboards/k8s-data-ingest-analysis03.png
  quickstarts/audit/k8s-data-ingestion-analysis/dashboards/k8s-data-ingest-analysis04.png
  quickstarts/audit/k8s-log-ingestion-analysis/config.yaml
  quickstarts/audit/k8s-log-ingestion-analysis/dashboards/k8s-log-ingest-breakdown.json
  quickstarts/audit/k8s-log-ingestion-analysis/dashboards/k8s-log-ingest-breakdown.png
  quickstarts/audit/log-ingestion-analysis/config.yml
  quickstarts/audit/log-ingestion-analysis/dashboards/log-analysis.json
  quickstarts/audit/log-ingestion-analysis/dashboards/log-analysis.png
  quickstarts/audit/log-ingestion-analysis/icon.jpeg
  quickstarts/audit/log-ingestion-analysis/logo.png
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/config.yml
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality.json
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality1.jpg
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality2.jpg
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality3.jpg
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality4.jpg
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/icon.png
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/logo.png
  quickstarts/audit/pomi-data-ingestion-analysis/config.yaml
  quickstarts/audit/pomi-data-ingestion-analysis/dashboards/pomi-stats.json
  quickstarts/audit/pomi-data-ingestion-analysis/dashboards/pomi-stats1.jpg
  quickstarts/audit/pomi-data-ingestion-analysis/dashboards/pomi-stats2.jpg
Labels: waiting on contributor

#542 fix(Quickstarts): Fixed a typo
  CONTRIBUTING.md
Labels: triage-needed

#556 chore: formatting updates for dashboard
  quickstarts/network-routers-and-switches/dashboards/network-routers-and-switches.json
Labels: triage-needed

#558 feat(pack): Added React Native
  quickstarts/react-native/alerts/LowApdexScore.yml
  quickstarts/react-native/alerts/TransactionError.yml
  quickstarts/react-native/config.yml
  quickstarts/react-native/dashboards/ReactNative.png
  quickstarts/react-native/dashboards/react-native.json
Labels: triage-needed

#541 Add mlops/superwise
  install/mlops/superwise/install.yml
  quickstarts/mlops/superwise/config.yml
  quickstarts/mlops/superwise/dashboards/superwise.json
  quickstarts/mlops/superwise/dashboards/superwise.png
  quickstarts/mlops/superwise/icon.png
  quickstarts/mlops/superwise/logo.png
Labels: waiting on contributor

#555 chore(update documentation): Added a hosted PDF and updated docs link
  quickstarts/gigamon/Gigamon New Relic Integration.pdf
  quickstarts/gigamon/config.yml
  quickstarts/gigamon/dashboards/gigamon-hawk.json
Labels: waiting on contributor

#564 Fix Account ID Issue
  quickstarts/mlops/superwise/dashboards/superwise.json
Labels: triage-needed

#548 feat(pack): Added Port monitoring
  quickstarts/port-monitoring/dashboards/port-monitoring.json
  quickstarts/port-monitoring/dashboards/port-monitoring.png
Labels: in-review

#563 feat(pack): Added Curb
  quickstarts/ruby/curb/alerts/CPUUtilization.yml
  quickstarts/ruby/curb/alerts/HighMemoryUsage.yml
  quickstarts/ruby/curb/alerts/LowApdexScore.yml
  quickstarts/ruby/curb/alerts/TransactionError.yml
  quickstarts/ruby/curb/config.yml
  quickstarts/ruby/curb/dashboards/Curb.png
  quickstarts/ruby/curb/dashboards/Curb2.png
  quickstarts/ruby/curb/dashboards/Curb3.png
  quickstarts/ruby/curb/dashboards/curb.json
  quickstarts/ruby/curb/images/Errors.png
  quickstarts/ruby/curb/images/Transactions.png
  quickstarts/ruby/curb/images/VM-metrics.png
Labels: triage-needed

#395 Add mlops/dagshub
  install/mlops/dagshub/install.yml
  quickstarts/mlops/dagshub/config.yml
  quickstarts/mlops/dagshub/dashboards/dagshub.json
  quickstarts/mlops/dagshub/dashboards/dagshub.png
  quickstarts/mlops/dagshub/icon.svg
  quickstarts/mlops/dagshub/logo.svg
Labels: in-review, waiting on contributor

#573 feat(Integration): Aporia Integration
  install/mlops/aporia/install.yml
  quickstarts/mlops/aporia/config.yml
  quickstarts/mlops/aporia/dashboards/aporia.json
  quickstarts/mlops/aporia/dashboards/aporia.png
  quickstarts/mlops/aporia/logo.svg
Labels: triage-needed

#569 chore: updates logos
  CONTRIBUTING.md
  quickstarts/audit/account-data-ingestion-analysis/config.yml
  quickstarts/audit/account-data-ingestion-analysis/logo.png
  quickstarts/audit/audit-events-analysis/config.yaml
  quickstarts/audit/audit-events-analysis/logo.png
  quickstarts/audit/k8s-data-ingestion-analysis/config.yaml
  quickstarts/audit/k8s-data-ingestion-analysis/logo.svg
  quickstarts/audit/k8s-log-ingestion-analysis/config.yaml
  quickstarts/audit/k8s-log-ingestion-analysis/logo.svg
  quickstarts/audit/pomi-data-ingestion-analysis/config.yaml
  quickstarts/audit/pomi-data-ingestion-analysis/logo.svg
  quickstarts/aws/aws-elemental-mediapackage-vod/config.yml
  quickstarts/aws/aws-elemental-mediapackage-vod/logo.png
  quickstarts/aws/aws-fsx/config.yml
  quickstarts/aws/aws-fsx/logo.png
  quickstarts/aws/aws-outposts/config.yml
  quickstarts/aws/aws-outposts/logo.png
  quickstarts/aws/aws-x-ray/config.yml
  quickstarts/aws/aws-x-ray/logo.png
  quickstarts/azure/azure-power-bi-dedicated-capacities/config.yml
  quickstarts/azure/azure-power-bi-dedicated-capacities/logo.png
  quickstarts/browser/config.yml
  quickstarts/browser/logo.png
  quickstarts/dotnet/iis/config.yml
  quickstarts/dotnet/iis/logo.svg
  quickstarts/dotnet/umbraco/config.yml
  quickstarts/dotnet/umbraco/logo.svg
  quickstarts/full-story/config.yml
  quickstarts/full-story/logo.png
  quickstarts/golang/gin/config.yml
  quickstarts/golang/gin/logo.png
  quickstarts/golang/lambda-go/config.yml
  quickstarts/golang/lambda-go/logo.png
  quickstarts/golang/logrus/config.yml
  quickstarts/golang/logrus/logo.png
  quickstarts/golang/logxi/config.yml
  quickstarts/golang/logxi/logo.svg
  quickstarts/golang/micro/config.yml
  quickstarts/golang/micro/logo.svg
  quickstarts/golang/mux/config.yml
  quickstarts/golang/mux/logo.png
  quickstarts/golang/nats/config.yml
  quickstarts/golang/nats/logo.svg
  quickstarts/golang/zap/config.yml
  quickstarts/golang/zap/logo.svg
  quickstarts/infrastructure/config.yml
  quickstarts/infrastructure/logo.png
  quickstarts/java/asynchttpclient/config.yml
  quickstarts/java/asynchttpclient/logo.svg
  quickstarts/java/websphere-liberty-profile/config.yml
  quickstarts/java/websphere-liberty-profile/logo.svg
  quickstarts/lamp/config.yml
  quickstarts/lamp/logo.png
  quickstarts/node-js/hapi/config.yml
  quickstarts/node-js/hapi/logo.png
  quickstarts/okhttp/config.yml
  quickstarts/okhttp/logo.png
Labels: in-review

#549 Require logo in the schema
  CONTRIBUTING.md
  utils/__tests__/validate_quickstarts.test.js
  utils/check-missing-logos.js
  utils/schemas/main_config.json
Labels: triage-needed

#576 feat(aws): add generalized aws quickstart
  quickstarts/aws/amazon-web-services/config.yml
  quickstarts/aws/amazon-web-services/logo.svg
Labels: triage-needed

#577 fix(aws): use larger logo
  quickstarts/aws/amazon-web-services/logo.svg
Labels: triage-needed

#578 fix(aws): link to aws integrations overview pane
  quickstarts/aws/amazon-web-services/config.yml
Labels: triage-needed

#579 feat: label pr's based on what files have changed
  .github/workflows/pr-open.yml
Labels: triage-needed

#575 style(macOS): Change `Mac OS` to `macOS`
  quickstarts/macos/config.yml
Labels: improved-quickstart

#586 chore: updated couchbase config
  README.md
  quickstarts/couchbase/config.yml
Labels: triage-needed, improved-quickstart

#588 chore: update episerver cms
  quickstarts/dotnet/episerver-cms/config.yml
Labels: improved-quickstart

#591 chore: adds generic new relic logo
  CONTRIBUTING.md
  images/ newrelic-generic-logo.svg
Labels: triage-needed

#589 chore: update description and summary for netty
  quickstarts/java/netty/config.yml
Labels: triage-needed, improved-quickstart

#590 feat: adding network syslog quickstart
  install/network/syslog/install.yml
  quickstarts/network-syslog/config.yml
  quickstarts/network-syslog/dashboards/network-syslog.json
  quickstarts/network-syslog/dashboards/network-syslog.png
  quickstarts/network-syslog/logo.svg
Labels: new-quickstart

#587 Jumpstart - Quickstart
  install/third-party/jumpstart/install.yml
  quickstarts/Jumpstart - Quickstart/alerts/baseline-alert.yml
  quickstarts/Jumpstart - Quickstart/alerts/outlier-alert.yml
  quickstarts/Jumpstart - Quickstart/alerts/static-alert.yml
  quickstarts/Jumpstart - Quickstart/config.yml
  quickstarts/Jumpstart - Quickstart/dashboards/Jumpstart.json
  quickstarts/Jumpstart - Quickstart/dashboards/Jumpstart01.png
  quickstarts/Jumpstart - Quickstart/logo.png
Labels: in-review, waiting on contributor, new-quickstart

#593 chore: update DB to add new syslog functionality and SNMP Traps
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality.json
Labels: triage-needed, improved-quickstart

#594 feat(Integration): Comet Integration
  install/mlops/comet/install.yml
  quickstarts/mlops/comet/config.yml
  quickstarts/mlops/comet/dashboards/comet.json
  quickstarts/mlops/comet/dashboards/comet.png
  quickstarts/mlops/comet/logo.png
Labels: triage-needed, new-quickstart

#595 chore: update quickstart summary and description
  quickstarts/python/feedparser/config.yml
Labels: triage-needed, improved-quickstart

#597 feat(packs) Added APM foundation to C pack
  quickstarts/c/alerts/CPUUtilization.yml
  quickstarts/c/alerts/HighMemoryUsage.yml
  quickstarts/c/alerts/LowApdexScore.yml
  quickstarts/c/alerts/TransactionError.yml
  quickstarts/c/dashboards/C.png
  quickstarts/c/dashboards/C2.png
  quickstarts/c/dashboards/C3.png
  quickstarts/c/dashboards/c.json
Labels: triage-needed

#601 feat: Add nerdlet to the comet quickstart
  install/mlops/comet/install.yml
Labels: triage-needed

#600 feat(pack) Added Azure Postgresql pack
  quickstarts/azure/azure-postgresql/config.yml
  quickstarts/azure/azure-postgresql/dashboards/azure-postgresql.json
  quickstarts/azure/azure-postgresql/dashboards/azure-postgresql.png
Labels: triage-needed, improved-quickstart

#599 feat(pack) Added Azure Storage pack
  quickstarts/azure/azure-storage/config.yml
  quickstarts/azure/azure-storage/dashboards/azure-storage.json
  quickstarts/azure/azure-storage/dashboards/azure-storage.png
Labels: triage-needed, improved-quickstart

#602 2 main changes. 1. Changed dir name from 'Jumpstart - Quickstart' to 'jumpstart'. 2. updated logos for NR-Kentick quickstarts.
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/config.yml
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/logo.png
  quickstarts/audit/network-data-ingest-and-cardinality-analysis/logo.svg
  quickstarts/jumpstart/alerts/baseline-alert.yml
  quickstarts/jumpstart/alerts/outlier-alert.yml
  quickstarts/jumpstart/alerts/static-alert.yml
  quickstarts/jumpstart/config.yml
  quickstarts/jumpstart/dashboards/Jumpstart.json
  quickstarts/jumpstart/dashboards/Jumpstart01.png
  quickstarts/jumpstart/logo.png
  quickstarts/network-flow-devices/config.yml
  quickstarts/network-flow-devices/logo.png
  quickstarts/network-flow-devices/logo.svg
  quickstarts/network-routers-and-switches/config.yml
  quickstarts/network-routers-and-switches/logo.png
  quickstarts/network-routers-and-switches/logo.svg
Labels: triage-needed

#592 Fix for PR 584
  quickstarts/python/feedparser/config.yml
Labels: in-review, improved-quickstart
