Repository newrelic/newrelic-quickstarts, pull requests merged in 2024-04, with the labels that each got.

#2318 Druid Quickstart
  alert-policies/apache-druid/failedQuery.yml
  alert-policies/apache-druid/jvmMemoryUsage.yml
  dashboards/apache-druid/apache-druid01.png
  dashboards/apache-druid/apache-druid02.png
  dashboards/apache-druid/apache-druid03.png
  dashboards/apache-druid/apache-druid04.png
  dashboards/apache-druid/dashboard.json
  data-sources/apache-druid/config.yml
  data-sources/apache-druid/logo.png
  quickstarts/apache-druid/config.yml
  quickstarts/apache-druid/logo.png
Labels: new-quickstart, Tara

#2350 Updated the Document URL's
  data-sources/pagerduty/config.yml
  data-sources/xmatters/config.yml
  install/third-party/vmware-tanzu/install.yml
  quickstarts/aws/aws-iot-twinmaker/config.yml
  quickstarts/full-stack-observability/config.yml
  quickstarts/infrastructure/config.yml
  quickstarts/pagerduty/pagerduty/config.yml
  quickstarts/pixie/config.yml
  quickstarts/vmware/vmware-tanzu/config.yml
  quickstarts/xmatters/config.yml
Labels: Tara

#2351 Updated "NR1_addData" keyword
  quickstarts/active-directory/config.yml
  quickstarts/adobe-commerce-business-insights/config.yml
  quickstarts/ads/web/ads-web-gpt/config.yml
  quickstarts/ads/web/ads-web-prebid/config.yml
  quickstarts/aerospike/config.yml
  quickstarts/ajax/config.yml
  quickstarts/aws/amazon-api-gateway/config.yml
  quickstarts/aws/aws-apprunner/config.yml
  quickstarts/gcp/gcp-alloydb/config.yml
  quickstarts/oma-aqm/config.yml
Labels: Tara

#2349 fix(amazon timestream): Updated the alerts titles and description alignment.
  alert-policies/amazon-timestream/MagneticStoreRejectedUploadSystemFailures.yml
  alert-policies/amazon-timestream/MagneticStoreRejectedUploadUserFailures.yml
  alert-policies/amazon-timestream/SystemErrors.yml
  alert-policies/amazon-timestream/UserErrors.yml
Labels: Tara

#2352 NR-255641: Removed Cloudformation custom resource quickstart.
  data-sources/alert-cloudformation-resource/config.yml
  data-sources/alert-cloudformation-resource/logo.jpg
  install/third-party/newrelic-alert-cloudformation-resource/install.yml
  quickstarts/aws/newrelic-alert-cloudformation-resource/config.yaml
  quickstarts/aws/newrelic-alert-cloudformation-resource/logo.jpg
Labels: Tara

#2364 Updated "NR1_addData" keyword to quickstarts
  quickstarts/aws/amazon-appstream/config.yml
  quickstarts/aws/amazon-aurora/config.yml
  quickstarts/aws/amazon-backup/config.yml
  quickstarts/aws/amazon-cloudsearch/config.yml
  quickstarts/aws/amazon-cloudwatch-internet-monitor/config.yml
  quickstarts/aws/amazon-cloudwatch-network-monitor/config.yml
  quickstarts/aws/amazon-codebuild/config.yml
  quickstarts/aws/amazon-database-migration-service/config.yml
  quickstarts/aws/amazon-datasync/config.yml
  quickstarts/aws/amazon-eks-on-aws-fargate/config.yml
  quickstarts/aws/amazon-elastictranscoder/config.yml
  quickstarts/aws/amazon-gamelift/config.yml
  quickstarts/aws/amazon-inspector/config.yml
  quickstarts/aws/amazon-keyspaces/config.yml
  quickstarts/aws/amazon-kinesis-firehose/config.yml
  quickstarts/aws/amazon-linux/config.yml
  quickstarts/aws/amazon-mwaa/config.yml
  quickstarts/aws/amazon-rds-enhanced/config.yml
  quickstarts/aws/aws-lex/config.yml
  quickstarts/aws/aws-polly/config.yml
Labels: Tara

#2369 Updated envoy logo URL
  dashboards/envoy/envoy.json
Labels: Tara

#2367 Updated 'NR1_addData' keyword to quickstarts
  quickstarts/apache-flink/config.yml
  quickstarts/apache-hadoop/config.yml
  quickstarts/apache-traffic-server/config.yml
  quickstarts/apache-zooKeeper/config.yml
  quickstarts/aws/amazon-route53-resolver/config.yml
  quickstarts/aws/amazon-security-lake/config.yml
  quickstarts/aws/amazon-simpleworkflow/config.yml
  quickstarts/aws/amazon-timestream/config.yml
  quickstarts/aws/amazon-transfer-family/config.yml
  quickstarts/aws/amazon-vpc-lattice/config.yml
  quickstarts/aws/amazon-vpc-nat-gateway/config.yml
  quickstarts/aws/amazon-workmail/config.yml
  quickstarts/aws/amazon-workspaces-web/config.yml
  quickstarts/aws/amazon-workspaces/config.yml
  quickstarts/aws/aws-rekognition/config.yml
  quickstarts/aws/aws-textract/config.yml
  quickstarts/aws/aws-translate/config.yml
  quickstarts/aws/aws-verified-access/config.yml
  quickstarts/java/camel/config.yml
  quickstarts/python/amqplib/config.yml
Labels: Tara

#2371 Updated 'NR1_addData' to quickstarts
  quickstarts/apm-transaction-analysis/config.yaml
  quickstarts/apollo/apollo-server/config.yml
  quickstarts/argocd/config.yml
  quickstarts/atlassian/atlassian-jira/config.yml
  quickstarts/aws/aws-appsync/config.yml
  quickstarts/aws/aws-certificate-manager/config.yml
  quickstarts/aws/aws-chatbot/config.yml
  quickstarts/aws/aws-cloudwatch-plugin-for-logs/config.yml
  quickstarts/aws/aws-elemental-mediatailor/config.yml
  quickstarts/aws/aws-enhanced-monitoring/config.yml
  quickstarts/aws/aws-iot-twinmaker/config.yml
  quickstarts/aws/aws-lambda-telemetry-extension/config.yml
  quickstarts/aws/aws-network-firewall/config.yml
  quickstarts/aws/aws-nlb-alb/config.yml
  quickstarts/aws/aws-storage-gateway/config.yml
  quickstarts/aws/aws-transcribe/config.yml
  quickstarts/aws/aws-vpn/config.yml
  quickstarts/gcp/apigee-api/config.yml
  quickstarts/jira-errors/config.yml
  quickstarts/network-monitoring/arista-switches/config.yml
Labels: Tara

#2370 Removed Resmo quickstart
  quickstarts/resmo/config.yml
  quickstarts/resmo/logo.svg
Labels: Tara

#2376 Updated NR1_addData and NR1_sys keywords
  quickstarts/azure/azure-anomaly-detector/config.yml
  quickstarts/azure/azure-app-configuration/config.yml
  quickstarts/azure/azure-app-gateway/config.yml
  quickstarts/azure/azure-app-service-environment/config.yml
  quickstarts/azure/azure-app-service-plan/config.yml
  quickstarts/azure/azure-application-insights/config.yml
  quickstarts/azure/azure-automation-account/config.yml
  quickstarts/azure/azure-batch/config.yml
  quickstarts/azure/azure-bing-autosuggest/config.yml
  quickstarts/azure/azure-bing-custom-search/config.yml
  quickstarts/azure/azure-bing-search/config.yml
  quickstarts/azure/azure-bing-spell-check/config.yml
  quickstarts/azure/azure-bing-web-search/config.yml
  quickstarts/azure/azure-cdn-profile/config.yml
  quickstarts/azure/azure-cloud-services/config.yml
  quickstarts/azure/azure-cognitive-search/config.yml
  quickstarts/azure/azure-cognitive-service/config.yml
  quickstarts/azure/azure-computer-vision/config.yml
  quickstarts/azure/azure-container-registry/config.yml
  quickstarts/snowflake/config.yml
Labels: Tara

#2341 New Quickstart: Ray
  alert-policies/ray/ActiveNodes.yml
  alert-policies/ray/FreeDiskPercentage.yml
  alert-policies/ray/RPCHealthCheckLatency.yml
  dashboards/ray/ray-01.png
  dashboards/ray/ray-02.png
  dashboards/ray/ray-03.png
  dashboards/ray/ray-04.png
  dashboards/ray/ray.json
  data-sources/ray/config.yml
  data-sources/ray/logo.svg
  quickstarts/ray/config.yml
  quickstarts/ray/logo.svg
Labels: new-quickstart, Tara

#2382 Snowflake: Updated Dashboard and Alerts
  alert-policies/snowflake/FailedQueries.yml
  alert-policies/snowflake/QueuedQueries.yml
  alert-policies/snowflake/SpilledLocalStorage.yml
  alert-policies/snowflake/SpilledRemoteStorage.yml
  dashboards/snowflake/dashboard.json
  dashboards/snowflake/snowflake-1.png
  dashboards/snowflake/snowflake-2.png
  dashboards/snowflake/snowflake-3.png
  dashboards/snowflake/snowflake-4.png
  dashboards/snowflake/snowflake-5.png
  dashboards/snowflake/snowflake-6.png
  dashboards/snowflake/snowflake-7.png
  dashboards/snowflake/snowflake01.png
  dashboards/snowflake/snowflake02.png
  dashboards/snowflake/snowflake03.png
  dashboards/snowflake/snowflake04.png
  dashboards/snowflake/snowflake05.png
  dashboards/snowflake/snowflake06.png
Labels: Tara

#2362 feat: New singlestore quickstart
  dashboards/singlestore/dashboard.json
  dashboards/singlestore/dashboard1.png
  dashboards/singlestore/dashboard2.png
  dashboards/singlestore/dashboard3.png
  data-sources/singlestore/config.yml
  data-sources/singlestore/logo.png
  quickstarts/singlestore/config.yml
  quickstarts/singlestore/logo.png
Labels: product partnerships

#2375 feat(triton): Added new integration NVIDIA Triton.
  alert-policies/nvidia-triton/CpuUsedPercentage.yml
  alert-policies/nvidia-triton/RequestFailures.yml
  alert-policies/nvidia-triton/StorageUsagePercentage.yml
  dashboards/nvidia-triton/nvidia-triton-01.png
  dashboards/nvidia-triton/nvidia-triton-02.png
  dashboards/nvidia-triton/nvidia-triton-03.png
  dashboards/nvidia-triton/nvidia-triton.json
  data-sources/nvidia-triton/config.yml
  data-sources/nvidia-triton/logo.png
  quickstarts/nvidia-triton/config.yml
  quickstarts/nvidia-triton/logo.png
Labels: new-quickstart, Tara

#2380 Added the NR1_addData and NR1_sys keywords
  quickstarts/apis/logs/config.yml
  quickstarts/apis/metric/config.yml
  quickstarts/audit/log-ingestion-analysis/config.yml
  quickstarts/azure/azure-purview/config.yml
  quickstarts/golang/lambda-go/config.yml
  quickstarts/golang/logrus/config.yml
  quickstarts/golang/logxi/config.yml
  quickstarts/k6-prometheus/config.yml
  quickstarts/kubernetes-prometheus/config.yml
  quickstarts/lamp/config.yml
  quickstarts/lampy/config.yml
  quickstarts/launchdarkly/config.yml
  quickstarts/lighthouse/config.yml
  quickstarts/lighttpd/config.yml
  quickstarts/loadmill/config.yml
  quickstarts/magento-business-insights/config.yml
  quickstarts/mean/config.yml
  quickstarts/mern/config.yml
  quickstarts/mevn/config.yml
  quickstarts/mssql-custom-queries/config.yml
Labels: Tara

#2374 Updated doc URL's for AI quickstarts
  quickstarts/amazon-bedrock/config.yml
  quickstarts/mlops/langchain/config.yml
  quickstarts/openai/config.yaml
Labels: Tara

#2388 Updated "NR1_addaData" and "NR1_sys" for quickstarts
  quickstarts/azure/azure-content-moderator/config.yml
  quickstarts/azure/azure-content-safety/config.yml
  quickstarts/azure/azure-custom-vision-prediction/config.yml
  quickstarts/azure/azure-custom-vision-training/config.yml
  quickstarts/azure/azure-data-box-edge/config.yml
  quickstarts/azure/azure-data-explorer/config.yml
  quickstarts/azure/azure-data-lake-analytics/config.yml
  quickstarts/azure/azure-data-lake-storage/config.yml
  quickstarts/azure/azure-data-share/config.yml
  quickstarts/azure/azure-datafactories/config.yml
  quickstarts/azure/azure-device-provisioning-service/config.yml
  quickstarts/azure/azure-disk-storage/config.yml
  quickstarts/azure/azure-dns-zones/config.yml
  quickstarts/azure/azure-event-grid-domains/config.yml
  quickstarts/azure/azure-event-grid-partner-namespaces/config.yml
  quickstarts/azure/azure-event-grid-partner-topics/config.yml
  quickstarts/azure/azure-event-grid-subscriptions/config.yml
  quickstarts/azure/azure-event-grid-system-topics/config.yml
  quickstarts/azure/azure-event-grid-topics/config.yml
  quickstarts/azure/azure-event-hubs/config.yml
  quickstarts/azure/azure-face-api/config.yml
Labels: Tara
