Repository newrelic/newrelic-quickstarts, pull requests merged in 2024-05, with the labels that each got.

#2393 Updated NR1_addData and NR1_sys keywords for quickstarts
  quickstarts/ansible-automation-controller/config.yml
  quickstarts/audit/pomi-data-ingestion-analysis/config.yaml
  quickstarts/notification-channels/servicenow-notifications/config.yml
  quickstarts/observability-as-code/pulumi/config.yml
  quickstarts/python/psycopg2/config.yml
  quickstarts/python/pyelasticsearch/config.yml
  quickstarts/python/pymongo/config.yml
  quickstarts/quantum-metric/config.yml
  quickstarts/rafay/config.yml
  quickstarts/redhat/red-hat-enterprise-linux/config.yml
  quickstarts/redhat/red-hat-openshift/config.yml
  quickstarts/redis-otel/config.yml
  quickstarts/redis-prometheus/config.yml
  quickstarts/redmine/config.yml
  quickstarts/redpanda/config.yml
  quickstarts/roku/config.yml
  quickstarts/salesforce-eventlog-for-logs/config.yml
  quickstarts/sendgrid/config.yml
  quickstarts/sendmail/config.yml
  quickstarts/shopify/config.yml
Labels: Tara

#2403 Updated 'NR1_addData' and 'NR1_sys' to quickstarts
  quickstarts/apis/trace/config.yml
  quickstarts/node-js/typescript/config.yml
  quickstarts/notification-channels/slack-notifications/config.yml
  quickstarts/observability-as-code/terraform/config.yml
  quickstarts/signl4/config.yml
  quickstarts/skykit/config.yml
  quickstarts/sonarqube/config.yml
  quickstarts/squid-prometheus/config.yml
  quickstarts/stripe/config.yml
  quickstarts/suse-linux-enterprise-server/config.yml
  quickstarts/sybase/config.yml
  quickstarts/tidbcloud/config.yml
  quickstarts/traefik/config.yml
  quickstarts/velero-prometheus/config.yml
  quickstarts/video/video-android/config.yml
  quickstarts/video/video-chromecast/config.yml
  quickstarts/video/video-ios-tvos/config.yml
  quickstarts/video/video-web/video-web-akamai/config.yml
  quickstarts/video/video-web/video-web-html5/config.yml
  quickstarts/video/video-web/video-web-jwplayer/config.yml
Labels: Tara

#2387 Joseph/awsstoragelens
  dashboards/amazon-s3-storagelens/amazon-s3-storagelens.json
  dashboards/amazon-s3-storagelens/amazon-s3-storagelens01.png
  dashboards/amazon-s3-storagelens/amazon-s3-storagelens02.png
  quickstarts/aws/amazon-s3-storagelens/config.yml
  quickstarts/aws/amazon-s3-storagelens/logo.svg
Labels: product partnerships

#2399 Updated NR1_addData and NR1_sys keywords for quickstarts
  quickstarts/audit/account-data-ingestion-analysis/config.yml
  quickstarts/confluent-cloud/config.yml
  quickstarts/conviva/config.yml
  quickstarts/core-web-vitals/config.yml
  quickstarts/coredns/config.yml
  quickstarts/dapr/config.yml
  quickstarts/debian/config.yml
  quickstarts/docker-otel/config.yml
  quickstarts/dotnet/csla-dotnet/config.yml
  quickstarts/dotnet/dnn-community/config.yml
  quickstarts/dotnet/dnn-evoq/config.yml
  quickstarts/java/cxf/config.yml
  quickstarts/java/datastax-cassandra/config.yml
  quickstarts/java/derby/config.yml
  quickstarts/oma-bofu/config.yml
  quickstarts/oma-qf/config.yml
  quickstarts/python/django/config.yml
  quickstarts/ruby/curb/config.yml
  quickstarts/ruby/dalli/config.yml
  quickstarts/ruby/delayed-job/config.yml
Labels: Tara

#2398 Updated NR1_addData and NR1_sys keywords for quickstarts
  quickstarts/apm-change-tracking/config.yml
  quickstarts/boomi/config.yaml
  quickstarts/botolytics/config.yml
  quickstarts/browser-segment-investigation/config.yml
  quickstarts/calico/config.yml
  quickstarts/catchpoint/config.yml
  quickstarts/centos/config.yml
  quickstarts/cloudfoundry/config.yml
  quickstarts/cockroach-db/config.yml
  quickstarts/gcp/gcp-composer/config.yml
  quickstarts/java/coldfusion/config.yml
  quickstarts/network-monitoring/cisco-ip-sla-operations/config.yml
  quickstarts/network-monitoring/ciscoHardware/config.yml
  quickstarts/php/cakephp/config.yml
  quickstarts/php/codeigniter/config.yml
  quickstarts/python/bottle/config.yml
  quickstarts/python/celery/config.yml
  quickstarts/python/cherrypy/config.yml
  quickstarts/ruby/bunny/config.yml
Labels: Tara

#2404 Updated 'NR1_addData' and 'NR1_sys' to quickstarts
  quickstarts/apis/event/config.yml
  quickstarts/dojo/config.yml
  quickstarts/dotnet/episerver-cms/config.yml
  quickstarts/drupal/config.yml
  quickstarts/elixir/config.yml
  quickstarts/etcd/config.yml
  quickstarts/fivetran/config.yml
  quickstarts/fluent-bit-plugin-for-logs/config.yml
  quickstarts/flutter-android/config.yml
  quickstarts/golang/echo/config.yml
  quickstarts/java/ejb-session-beans/config.yml
  quickstarts/java/elasticsearch-query/config.yml
  quickstarts/node-js/express/config.yml
  quickstarts/notification-channels/email-notifications/config.yml
  quickstarts/python/facepy/config.yml
  quickstarts/python/falcon/config.yml
  quickstarts/python/fastapi/config.yml
  quickstarts/python/feedparser/config.yml
  quickstarts/python/flask/config.yml
  quickstarts/ruby/excon/config.yml
Labels: Tara

#2406 Updated 'NR1_addData' and 'NR1_sys' to quickstarts
  quickstarts/dotnet/fubumvc/config.yml
  quickstarts/flutter-ios/config.yml
  quickstarts/flutter-web/config.yml
  quickstarts/full-stack-observability/config.yml
  quickstarts/full-story/config.yml
  quickstarts/gcp/gcp-dedicated-interconnect/config.yml
  quickstarts/gcp/gcp-redis/config.yml
  quickstarts/gcp/google-app-engine/config.yml
  quickstarts/gcp/google-cloud-bigtable/config.yml
  quickstarts/github-repo/config.yml
  quickstarts/gitlab/config.yml
  quickstarts/golang/gin/config.yml
  quickstarts/golden-signals-dashboard/config.yml
  quickstarts/golden-signals-web/config.yml
  quickstarts/java/generic-jdbc/config.yml
  quickstarts/java/glassfish/config.yml
  quickstarts/python/gearman/config.yml
  quickstarts/python/gevent/config.yml
Labels: Tara

#2411 Removed keywords for APM category
  quickstarts/dotnet/blazor-server/config.yml
  quickstarts/java/camel/config.yml
  quickstarts/java/gcp-pubsub/config.yml
  quickstarts/java/jdbc-executebatch/config.yml
  quickstarts/java/websphere-liberty-profile/config.yml
  quickstarts/mean/config.yml
  quickstarts/mern/config.yml
  quickstarts/mevn/config.yml
  quickstarts/php/odbc/config.yml
Labels: Tara

#2379 NVML Quickstart
  alert-policies/nvml/HighTemperature.yml
  dashboards/nvml/nvml.json
  dashboards/nvml/nvml01.png
  data-sources/nvml/config.yml
  data-sources/nvml/logo.png
  quickstarts/nvml/config.yml
  quickstarts/nvml/logo.png
Labels: new-quickstart, Tara, awaiting docs

#2415 feat: Apache mesos quickstart
  alert-policies/apache-mesos/errorTasks.yml
  alert-policies/apache-mesos/failedTasks.yml
  alert-policies/apache-mesos/lostTasks.yml
  dashboards/apache-mesos/apache-mesos.json
  dashboards/apache-mesos/apache-mesos01.png
  dashboards/apache-mesos/apache-mesos02.png
  dashboards/apache-mesos/apache-mesos03.png
  dashboards/apache-mesos/apache-mesos04.png
  data-sources/apache-mesos/config.yml
  data-sources/apache-mesos/logo.png
  quickstarts/apache-mesos/config.yml
  quickstarts/apache-mesos/logo.png
Labels: new-quickstart, Tara
