Repository newrelic/newrelic-quickstarts, pull requests merged in 2024-02, with the labels that each got.

#2158 Update gitlab_dashboard.json
  dashboards/gitlab/gitlab_dashboard.json
Labels: stale

#2276 [Product Partnerships] Added AWS Workspaces web
  alert-policies/amazon-workspaces-web/SessionFailure.yml
  dashboards/amazon-workspaces-web/amazon-workspaces-web.json
  dashboards/amazon-workspaces-web/amazon-workspaces-web.png
  quickstarts/aws/amazon-workspaces-web/config.yml
  quickstarts/aws/amazon-workspaces-web/logo.png
Labels: waiting on contributor, product partnerships, northstar

#2271 Chore: delete the jumpstart quickstart
  dashboards/jumpstart/Jumpstart.json
  dashboards/jumpstart/Jumpstart01.png
  data-sources/jumpstart/config.yml
  data-sources/jumpstart/logo.svg
  install/third-party/jumpstart/install.yml
  quickstarts/jumpstart/config.yml
  quickstarts/jumpstart/logo.svg
Labels: waiting on owning team

#2300 Updated the description of k6 Prometheus (remote write)
  quickstarts/k6-prometheus/config.yml
Labels: Tara

#2296 Updated the Prometheus remote write doc URL
  quickstarts/prometheus-remote-write/config.yml
Labels: Tara

#2299 Updating 4 partner data sources to point to their Install configs
  data-sources/cribl/config.yml
  data-sources/delphix/config.yml
  data-sources/gigamon-appinsights/config.yml
  data-sources/netlify-builds/config.yml
Labels: waiting on contributor
